# Generated by Django 6.0.3 on 2026-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moguffy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_file",
        ),
        migrations.AddField(
            model_name="song",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
