# Generated by Django 6.0.3 on 2026-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moguffy", "0002_remove_song_audio_file_song_audio_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="song_videos/"),
        ),
    ]
