# Generated by Django 6.0.3 on 2026-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moguffy", "0003_song_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="song",
            name="playlist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="audio",
            field=models.FileField(default=False, upload_to="songs/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(default=False, upload_to="images/"),
            preserve_default=False,
        ),
    ]
