# Generated by Django 6.0.3 on 2026-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moguffy", "0004_song_liked_song_playlist_alter_song_audio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="playlist",
        ),
        migrations.AlterField(
            model_name="song",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("songs", models.ManyToManyField(to="Moguffy.song")),
            ],
        ),
    ]
