# Generated by Django 6.0.3 on 2026-03-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Moguffy", "0005_remove_song_playlist_alter_song_audio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="name",
        ),
        migrations.AddField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(blank=True, to="Moguffy.song"),
        ),
        migrations.AlterField(
            model_name="song",
            name="audio",
            field=models.FileField(default=1, upload_to="songs/"),
            preserve_default=False,
        ),
    ]
